# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, -10, 801, 451))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../Pictures/muscle_cat.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.gj = QtWidgets.QPushButton(self.centralwidget)
        self.gj.setGeometry(QtCore.QRect(40, 470, 191, 71))
        self.gj.setObjectName("gj")
        self.hj = QtWidgets.QPushButton(self.centralwidget)
        self.hj.setGeometry(QtCore.QRect(540, 460, 211, 71))
        self.hj.setObjectName("hj")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
# hi
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.gj.clicked.connect(self.show_gj)
        self.hj.clicked.connect(self.show_hj)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gj.setText(_translate("MainWindow", "규진"))
        self.hj.setText(_translate("MainWindow", "형준"))

    def show_gj(self):
        self.photo.setPixmap(QtGui.QPixmap("muscle_cat.jpg"))

    def show_hj(self):
        self.photo.setPixmap(QtGui.QPixmap("thin_cat.jpg"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
