# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 290, 461, 201))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.Videos = QtWidgets.QMenu(self.menubar)
        self.Videos.setObjectName("Videos")
        self.Analyer = QtWidgets.QMenu(self.menubar)
        self.Analyer.setObjectName("Analyer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_video = QtWidgets.QAction(MainWindow)
        self.open_video.setObjectName("open_video")
        self.screenshot_path = QtWidgets.QAction(MainWindow)
        self.screenshot_path.setObjectName("screenshot_path")
        self.reset = QtWidgets.QAction(MainWindow)
        self.reset.setObjectName("reset")
        self.menuFile.addAction(self.open_video)
        self.menuFile.addAction(self.screenshot_path)
        self.menuFile.addAction(self.reset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.Videos.menuAction())
        self.menubar.addAction(self.Analyer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "이거시 비디오다... "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Videos.setTitle(_translate("MainWindow", "Videos"))
        self.Analyer.setTitle(_translate("MainWindow", "Analyer"))
        self.open_video.setText(_translate("MainWindow", "Open vdieo"))
        self.screenshot_path.setText(_translate("MainWindow", "screenshot path"))
        self.reset.setText(_translate("MainWindow", "reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
